In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data_Salary.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' nan 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 64000.0]
 ['France' 35.0 58000.0]
 ['Spain' 39.0 52000.0]
 ['France' 48.0 nan]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Spain' nan 50000.0]
 ['France' 55.0 nan]
 ['Germany' 32.0 70000.0]
 ['Spain' 43.0 62000.0]
 ['Germany' 37.0 54000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [6]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 40.61538461538461 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 64000.0]
 ['France' 35.0 58000.0]
 ['Spain' 39.0 52000.0]
 ['France' 48.0 61153.846153846156]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Spain' 40.61538461538461 50000.0]
 ['France' 55.0 61153.846153846156]
 ['Germany' 32.0 70000.0]
 ['Spain' 43.0 62000.0]
 ['Germany' 37.0 54000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 40.61538461538461 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 64000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 39.0 52000.0]
 [1.0 0.0 0.0 48.0 61153.846153846156]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 40.61538461538461 50000.0]
 [1.0 0.0 0.0 55.0 61153.846153846156]
 [0.0 1.0 0.0 32.0 70000.0]
 [0.0 0.0 1.0 43.0 62000.0]
 [0.0 1.0 0.0 37.0 54000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
print(X_train)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 40.61538461538461 50000.0]
 [0.0 1.0 0.0 40.0 64000.0]
 [0.0 0.0 1.0 40.61538461538461 48000.0]
 [0.0 0.0 1.0 43.0 62000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 37.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 32.0 70000.0]
 [1.0 0.0 0.0 55.0 61153.846153846156]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(X_test)

[[0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 48.0 61153.846153846156]
 [0.0 0.0 1.0 39.0 52000.0]]


In [14]:
print(y_train)

[0 1 1 1 0 0 1 1 0 1 0 1]


In [15]:
print(y_test)

[0 1 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [17]:
print(X_train)

[[0.0 1.0 0.0 -1.5205383553589473 -0.8212726980812227]
 [0.0 0.0 1.0 0.038601902519948245 -1.2355606233865444]
 [0.0 1.0 0.0 -0.05178303996578453 0.21444711518208157]
 [0.0 0.0 1.0 0.038601902519948245 -1.4427045860392054]
 [0.0 0.0 1.0 0.3888435546521643 0.007303152529420716]
 [1.0 0.0 0.0 0.5357190861914806 1.043022965792725]
 [0.0 1.0 0.0 -0.4924096345837334 -0.8212726980812227]
 [1.0 0.0 0.0 -0.4924096345837334 0.5251630591610729]
 [0.0 1.0 0.0 1.4169722754273784 2.1823147603823596]
 [0.0 1.0 0.0 -1.2267872922803147 0.8358790031400641]
 [1.0 0.0 0.0 2.1513499331239596 -0.08033467782362788]
 [1.0 0.0 0.0 -0.786160697662366 -0.406984772775901]]


In [18]:
print(X_test)

[[0.0 0.0 1.0 -0.3455341030444171 -0.09626882879690972]
 [1.0 0.0 0.0 1.1232212123487457 -0.08033467782362788]
 [0.0 0.0 1.0 -0.19865857150510083 -1.0284166607338836]]
